spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://db:5432/walletdb  # Database connection for Docker environment
    username: postgres
    password: Ab123456
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false  # Disable open-in-view to avoid performance issues

  rabbitmq:
    host: rabbitmq  # Connect to RabbitMQ container
    port: 5672
    username: guest
    password: guest

# Logging level for the Wallet Service
logging:
  level:
    com.jack.walletservice: INFO
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"

# SpringDoc settings for API documentation in Docker environment
springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui-custom.html
